
// This file has been generated by the GUI designer. Do not modify.
namespace libarduinotty.Widgets
{
	public partial class TransmitWidget
	{
		private global::Gtk.VBox VBox;
		private global::Gtk.HBox HBox;
		private global::Gtk.Alignment Alignment;
		private global::Gtk.ComboBoxEntry ComboBoxEntry;
		private global::Gtk.CheckButton CheckButton;
		private global::Gtk.ComboBox ComboBox;
		private global::Gtk.Button Button;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget libarduinotty.Widgets.TransmitWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "libarduinotty.Widgets.TransmitWidget";
			// Container child libarduinotty.Widgets.TransmitWidget.Gtk.Container+ContainerChild
			this.VBox = new global::Gtk.VBox ();
			this.VBox.Name = "VBox";
			this.VBox.Spacing = 6;
			// Container child VBox.Gtk.Box+BoxChild
			this.HBox = new global::Gtk.HBox ();
			this.HBox.Name = "HBox";
			this.HBox.Spacing = 6;
			// Container child HBox.Gtk.Box+BoxChild
			this.Alignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.Alignment.Name = "Alignment";
			// Container child Alignment.Gtk.Container+ContainerChild
			this.ComboBoxEntry = global::Gtk.ComboBoxEntry.NewText ();
			this.ComboBoxEntry.Name = "ComboBoxEntry";
			this.Alignment.Add (this.ComboBoxEntry);
			this.HBox.Add (this.Alignment);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.HBox [this.Alignment]));
			w2.Position = 0;
			// Container child HBox.Gtk.Box+BoxChild
			this.CheckButton = new global::Gtk.CheckButton ();
			this.CheckButton.CanFocus = true;
			this.CheckButton.Name = "CheckButton";
			this.CheckButton.Label = "";
			this.CheckButton.Active = true;
			this.CheckButton.DrawIndicator = true;
			this.CheckButton.UseUnderline = true;
			this.HBox.Add (this.CheckButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.HBox [this.CheckButton]));
			w3.Position = 1;
			w3.Expand = false;
			// Container child HBox.Gtk.Box+BoxChild
			this.ComboBox = global::Gtk.ComboBox.NewText ();
			this.ComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Bin"));
			this.ComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Oct"));
			this.ComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Dec"));
			this.ComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Hex"));
			this.ComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("ASCII"));
			this.ComboBox.Name = "ComboBox";
			this.ComboBox.Active = 4;
			this.HBox.Add (this.ComboBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.HBox [this.ComboBox]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child HBox.Gtk.Box+BoxChild
			this.Button = new global::Gtk.Button ();
			this.Button.Sensitive = false;
			this.Button.CanFocus = true;
			this.Button.Name = "Button";
			this.Button.UseUnderline = true;
			// Container child Button.Gtk.Container+ContainerChild
			global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w6 = new global::Gtk.HBox ();
			w6.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w6.Add (w7);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w9 = new global::Gtk.Label ();
			w6.Add (w9);
			w5.Add (w6);
			this.Button.Add (w5);
			this.HBox.Add (this.Button);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.HBox [this.Button]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			this.VBox.Add (this.HBox);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.VBox [this.HBox]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			this.Add (this.VBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.ComboBoxEntry.Changed += new global::System.EventHandler (this.OnComboBoxEntryChanged);
			this.ComboBoxEntry.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnComboBoxEntryKeyPressEvent);
			this.ComboBoxEntry.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnComboBoxEntryKeyReleaseEvent);
			this.ComboBox.Changed += new global::System.EventHandler (this.OnComboBoxChanged);
			this.Button.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		}
	}
}
